FROM opensuse/leap:42.3 as builder

# download and build Python 
RUN zypper --non-interactive install readline-devel sqlite3-devel libbz2-devel zlib-devel libopenssl-devel wget tar gcc make
RUN wget -O /root/Python-3.6.6.tar.xz https://www.python.org/ftp/python/3.6.6/Python-3.6.6.tar.xz && (cd /root; tar xf Python-3.6.6.tar.xz)
RUN (cd /root/Python-3.6.6; ./configure --enable-optimizations --enable-shared && make -j 8 build_all && make altinstall)

FROM opensuse/leap:42.3

# Copy built python to fresh image
COPY --from=builder /usr/local /usr/local
ENV AP_PYTHONHOME=/usr/local

# Add sample project to image
COPY core /opt/apamacore
COPY project /opt/project
COPY launch.sh /opt/launch.sh

# Launch image with correct settings to run project
ENTRYPOINT ["/opt/launch.sh"]
CMD ["correlator", "--config", "/opt/project"]

