FROM ubuntu:bionic

# Install python from main repository
RUN apt-get update && apt-get install -y python3.7 libpython3.7
ENV AP_PYTHONHOME=/usr

# Add sample project to image
COPY core /opt/apamacore
COPY project /opt/project
COPY launch.sh /opt/launch.sh

# Launch image with correct settings to run project
ENTRYPOINT ["/opt/launch.sh"]
CMD ["correlator", "--config", "/opt/project"]
