FROM centos:7 as builder

RUN yum install -y gcc openssl-devel bzip2-devel libffi-devel wget make
RUN wget -O /root/Python-3.7.4.tar.xz https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tar.xz && (cd /root; tar xf Python-3.7.4.tar.xz)
RUN (cd /root/Python-3.7.4; ./configure --enable-optimizations --enable-shared && make -j 8 build_all && make altinstall)

FROM centos:7

# Copy built python to fresh image
COPY --from=builder /usr/local /usr/local
ENV AP_PYTHONHOME=/usr/local

# Add sample project to image
COPY core /opt/apamacore
COPY project /opt/project
COPY launch.sh /opt/launch.sh

# Launch image with correct settings to run project
ENTRYPOINT ["/opt/launch.sh"]
CMD ["correlator", "--config", "/opt/project"]
